stages:
  - helm-package
  - build
  - deploy  

Helm Package:
  stage: helm-package
  image: dtzar/helm-kubectl:3.7.1
  script:
    - helm repo add --username gitlab-ci-token --password $CI_JOB_TOKEN gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm cm-push helm-charts/eco-franca-web gitlab
  environment:
    name: production
    kubernetes:
      namespace: production-eco-franca    
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-production$/'

Build:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.prod --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}
  environment:
    name: production
    kubernetes:
      namespace: production-eco-franca    
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-production$/'

Deploy to production:
  stage: deploy
  image: dtzar/helm-kubectl:3.6.3
  before_script:
    - mkdir $HOME/.kube
    - cp $KUBE_CONFIG_PRODUCTION $HOME/.kube/config
    - helm repo add --username gitlab-ci-token --password $CI_JOB_TOKEN gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
    - helm repo update
  script:
    - helm upgrade production-eco-franca-web --install -n production-eco-franca gitlab/eco-franca-web -f $VALUES_HELM
  environment:
    name: production
    kubernetes:
      namespace: production-eco-franca
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-production$/'    