replicaCount: 1

image:
  repository: registry.app.franca.sp.gov.br/unifacef/eco-franca/eco-franca-api
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: gitlab-registry
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

application:
  serverPort: 3000

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
